### ISSUE TITLE
Can it adapt to VS2022？

### ISSUE THREAD

**Issue by iop02008** [HJLebbink/asm-dude#141]
Can it adapt to VS2022？

**Comment by sinnrrr** [comment]
For now, you can use [ChASM](https://marketplace.visualstudio.com/items?itemName=ethicalblue.chasm)

**Comment by KsaNL** [comment]
See #128

**Comment by nixoneen1** [comment]
chASM just makes all of my assembly code blue. It doesn't help.  That's a bug or does it need any configurations? Asm dude please just make this thing for use in vs Community 2022.

**Comment by Drehrumbum** [comment]
Same here.  And yes, with chASM all lines are blue and this doesn't help much. 

I've re-installed the preview of AsmDude for VS2022 from the zip-file. This version worked well in the past. But now I always get an "the service microsoft.visualstudio.shell.interop.ivstasklist must be installed"- error, so there are no different colors for registers, mnemonics etc. anymore. High-lightning still works. Maybe one of the latest VS2022 updates caused this issue - or - I've thrashed my VS2022-installation by removing some of the not used components, lately. I'll ask google.

I hope, we'll get a official version of AsmDude soon, because it is one of the "must have" VS extensions!  Thanks for your work and all the best @HJLebbink!

**Comment by henkjan-sneller** [comment]
for VS2022 support, see https://github.com/SnellerInc/asm-dude/discussions/1
