### ISSUE TITLE
Struct not supported?

### ISSUE THREAD

**Issue by c0ca1ne** [HJLebbink/asm-dude#31]

**Comment by HJLebbink** [comment]
you mean NASM's struct as in: 
```
struc vertex
  .x  resq 1
  .y  resq 1
  .z  resq 1
endstruc
```
Or are you using a struct from another dialect?

**Comment by c0ca1ne** [comment]
about syntax coloring


![](http://image.prntscr.com/image/0f91fc3054c9448a9f25ef6ffbd45206.png)

![](http://image.prntscr.com/image/393c5e279b2b4ba5bec03214768bb9a3.png)

**Comment by HJLebbink** [comment]
Oh, you like the field names that make up the struct to have syntax coloring of some sort. That is not easy, since those words  are not keywords in the language. You like want to do things as:
```
String STRUCT
    size dw 100
    len dw 10
String ENDS

ASSUME eax:PTR String
mov ecx, [eax].size,
mov edx, [eax].len
ASSUME eax:nothing
```
and have the size in "[eax].size" with syntax coloring too?

I've never considered this, I'll put in on the TODO list.

**Comment by c0ca1ne** [comment]
Ok.
