### ISSUE TITLE
undefined label

### ISSUE THREAD

**Issue by francescogomez** [HJLebbink/asm-dude#40]
Hmm..

![](http://image.prntscr.com/image/8060a951e1644d3090e29e2cf8da195d.png)

**Comment by HJLebbink** [comment]
@francescogomez Recently I don't use MASM that often...

I've switched off PROTO defined labels because they created clashing label definitions. In your situation the ExitProcess label is not added to the label graph, hence the warning that it is not defined. I perhaps incorrectly assumed that the code of PROTO defined labels will be included elsewhere (eg. in an include).

If you think the warning is incorrect, I may find a way to fix this properly.

**Comment by HJLebbink** [comment]
Fixed in the next version after 1.7.3.8

**Comment by francescogomez** [comment]
It is work.


![](http://image.prntscr.com/image/46d15615d9ba4d9aa8634e9b1b52d6c8.png)

**Comment by francescogomez** [comment]
![](http://image.prntscr.com/image/102969875c534e5d92b9ae5f10777f25.png)

**Comment by HJLebbink** [comment]
Visual Studio is a strange beast; the warning squiggles and the error tasks in the error list are unrelated. I forgot to update te error list update code... 

Is fixed in the next version after 1.7.3.8
