### ISSUE TITLE
Options Menu Disappears After Restarting VS

### ISSUE THREAD

**Issue by TacticalMook** [HJLebbink/asm-dude#5]
The options menu (Tools > Options > AsmDude) disappears after restarting Visual Studio Community 2015 on Windows 10. Does not appear to be related to changing or using different themes.

100% repeatable

Workaround: Disable AsmDude, restart, enable AsmDude, restart. This workaround is rather inconvenient since VS must be restarted to apply changes to some options.

**Comment by HJLebbink** [comment]
Thanx for reporting this. I will look into it.

**Comment by TacticalMook** [comment]
A side effect is the plugin must be disabled/re-enabled to apply changes to options that require a restart. Simply restarting VS and not caring about the missing options menu won't apply changes to syntax highlighting colors, for example.

**Comment by HJLebbink** [comment]
Some observations:

1. AsmDude stores the user preferences in the Windows registry. Additionally, the AsmDude.pkgdef creates other registry entries. 

2. Sadly, uninstalling .vsix plugins do not properly cleanup their registry entries.

3. Starting visual studio with logging switched on ("C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe" /LOG c:/temp/VS2015log.xml) shows registry classes for package AsmDude. I assume these errors are symptoms of the options pages not showing.

4. Thoroughly removing all registry entry that come up when searching for AsmDude seem to solve the problem, but it does not seem to prevent the problem from occurring again. 

I’m still looking for a real solution.

**Comment by HJLebbink** [comment]
For reference,
- Stackoverflow question about this issue [here](http://stackoverflow.com/questions/36745401)
- MSDN question about this issue [here](https://social.msdn.microsoft.com/Forums/vstudio/en-US/c4c98a81-d236-4419-98f7-70de058ae8b0)

**Comment by HJLebbink** [comment]
Documentation for myself. 

Problem: after updating the extension (to version 2.5.2.11), the binaries of the previous version are still used (2.5.2.10). The version number Tools>Extension and Updates>AsmDude state the installed version (2.5.2.11) while the version number Help>About Microsoft Visual Studio states 2.5.2.10. Since version 2.5.2.10, the version number is also listen in Tools>Options>AsmDude in the first row.

Restarting VS does not update the version.

If you start VS with logging (devenv.exe /log) you can find a log entry that states that the version 2.5.2.10 is marked for deletion, but somehow it is not deleted.

```
<entry>
    <record>420</record>
    <time>2016/07/04 19:39:36.090</time>
    <type>Warning</type>
    <source>Extension Manager</source>
    <description>Extension will not be loaded because it is marked for deletion.</description>
 <path>C:\USERS\HENKJ\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\wterbevq.1zd\extension.vsixmanifest</path>
</entry>
```

If you disable the AsmDude plugin, restart VS, enable the plugin, restart VS, the version is updated. 

This problem can be reproduced by first installing version 2.5.2.10, and then overwriting it with version 2.5.2.11. The only difference between these two versions is the version number.

[AsmDude 2.5.2.10.vsix.zip](https://github.com/HJLebbink/asm-dude/files/346796/AsmDude.2.5.2.10.vsix.zip)
[AsmDude 2.5.2.11.vsix.zip](https://github.com/HJLebbink/asm-dude/files/346797/AsmDude.2.5.2.11.vsix.zip)

**Comment by HJLebbink** [comment]
Version 1.7.0.5 solves these issues (for me at least). If someone still sees these or similar problems, please let me know.
