### ISSUE TITLE
AsmDude hangs when folding: thread not STA

### ISSUE THREAD

**Issue by dwkrueger2** [HJLebbink/asm-dude#55]
I have to force kill Visual Studio when opening .asm that is being parsed by asm-dude
http://imgur.com/a/Qrmiv  occurs with ASM.DUDe 1.8.1.1 and 1.8.1.3
http://imgur.com/a/EDaaJ

**Comment by dwkrueger2** [comment]
http://imgur.com/a/rDchy
The last line Warning says somthing about

**Comment by dwkrueger2** [comment]
I think it might be related to the ;#region / ;#endregion tags

**Comment by HJLebbink** [comment]
A yes, known issue, seen it before, I thought I circumvented it. The thread doing the folding seems not to be STA (single-threaded apartment model), which is weird. I'll look into it.

**Comment by HJLebbink** [comment]
Thanks for bringing this to my attention. I have problems reproducing the STA issue on my setup. I've replaced the peek content that show up when code is collapsed with a string instead of a TextBlock. Creating the TextBlock seems to trigger the STA issue. Version 1.8.1.4 should have this fixed. But since I can't reproduce it I'm not sure whether it is really fixed. 

If you still experience this problem, would you mind sharing the code that reproduces this?
