### ISSUE TITLE
AsmDude very slow when loading large ASM files (about 550Kb)

### ISSUE THREAD

**Issue by rahucha** [HJLebbink/asm-dude#56]
Hi,

When I load a very large ASM file (I'm using a long generated ASM file) it hangs visual studio (2015)

If I rename the file as something different from ".asm" it loads correctly under Visual Studio (but of course, it's not parsed by AsmDude)

Thanks

**Comment by HJLebbink** [comment]
It ought to work with large files, that is, features will switch off when they observe they delay the user experience tens of seconds. But I can't recall trying AsmDude on such large files. If you have a large asm file that I can test with, that would speed up tracking the hang issue.

**Comment by HJLebbink** [comment]
Thanx for the large file. After a loading it I receive the following messages:

```
WARNING: SLOW: took LabelGraph 31.710 seconds to finish
WARNING: Performance of LabelGraph is horrible: disabling label analysis for test.asm.
WARNING: SLOW: took CodeFoldingTagger 61.554 seconds to finish
WARNING: Performance of CodeFoldingTagger is horrible: disabling folding for test.asm.
```

AsmDude disabled both code folding and label analysis. After which the Visual Studio is usable (although somewhat sluggish on my 8 year old computer). Since you cannot disable the label analysis in the options pages you cannot prevent the 1 minute hang when loading such large files, the next version (after 1.8.1.4) will sport an option which will allow you to disable label analysis. That will solve your problem.
