### ISSUE TITLE
Include Files don't get scanned

### ISSUE THREAD

**Issue by popebx** [HJLebbink/asm-dude#79]
Using VS2015 and INFO: Loaded AsmDude version 1.9.4.2 (13.01.2018 16:37:53)

Looks like the scanner doesnt really scan kernel32.inc 
I tried to move the masm32\include to C: but won't fix it,

ASMSim Output, when i tried to include \masm32\include\kernel32.inc (both compile just fine)

> WARNING: could not highlight string "\kernel32\.inc"; e="\kernel32\.inc" is being analyzed - Malformed Reference:, (Wrong Name) \k<...> 

Had to translate the error message, so its not the original words

![image](https://user-images.githubusercontent.com/26490494/39543326-22fbeb40-4e4b-11e8-9cb6-304d3ed84808.png)

**Comment by HJLebbink** [comment]
Several possible issues:

1] When you have a file "program.asm" with the content "include kernel32.inc", AsmDude looks for the file "kernel32.inc" in the same directory as "program.asm". Thus, "include inc\my_function.asm" will scan the file my_function.asm in the directory inc, and inc is located in the directory of "program.asm". This should work.

2] Having said that, the recent updates to VS2017 introduced a lot of suddle regressions. I think your version my not load the includes because of a silly threading issue. Programming extensions is no fun.

I'll look into it.
