### ISSUE TITLE
System.IO.FileNotFoundException Looking for C:\Users\henk\Dropbox...

### ISSUE THREAD

**Issue by pablohawk** [HJLebbink/asm-dude#90]
I'm getting the following error in Visual Studio since an update to AsmDude.

The troubling thing about the error is that it references a file in a C:> user-folder dropbox.  Can you tell me where i can fix this issue so I don't get the error on startup?

<description>System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.CodeAnalysis.CSharp.Scripting, Version=2.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.CodeAnalysis.CSharp.Scripting, Version=2.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&apos;&#x000D;&#x000A;   at AsmTools.ExpressionEvaluator.Evaluate_Constant(String str, Boolean isCapitals)&#x000D;&#x000A;   at AsmTools.AsmSourceTools.Evaluate_Constant(String token, Boolean isCapitals)&#x000D;&#x000A;   at AsmDude.MasmTokenTagger.&lt;GetTags&gt;d__20.MoveNext() in C:\Users\henk\Dropbox\sc\GitHub\asm-dude\VS\CSHARP\asm-dude-vsix\SyntaxHighlighting\MasmTokenTagger.cs:line 189&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__39.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>

**Comment by HJLebbink** [comment]
The Microsoft.CodeAnalysis.CSharp.Scripting assembly is not found. What version of VS and AsmDude are you using?

**Comment by tjdowns** [comment]
Not interested.


-----BEGIN PGP PUBLIC KEY BLOCK----- Version: Keybase OpenPGP v1.0.0
Comment: https://keybase.io/crypto
xo0EW6ve1wEEANzWrHSRdb53la8ZDnFRYdoJbadLWpKmqJaRLFM6hxvU0YYOSaGn
b7iF5l2XRhkT2MIbWu5TuY1Las3BoR6bpZQk4AR84512lVqcQCgXH9aDdaRZr5Z4
bWGo/kzZ5xlhaGuJCebowocWMacy07GZwtXaTO2+dq9FlQJ1nvbNcX2HABEBAAHN
J1Rob21hcyBKLiBEb3ducyA8dGpkb3duc0Bob3RtYWlsLmNvLnVrPsKtBBMBCgAX
BQJbq97XAhsvAwsJBwMVCggCHgECF4AACgkQW+KCXRZct2872wP+J078WteXeh5O
Qs6hkKpCtWS06RzJ5c1zzLQZ+rmyWFmFbP16KP25L7SWc0gPAcQ+YvAayLEo/v7v
UTCLXtT2WM35v81iNWvq42wwoFiUjAjzvJZdmlxE0Jn5hxezes2hWINb21KOkzlG
orA7LCPJfPfQ4IQewd+9qzDYdwbWFinOjQRbq97XAQQAq/mXroCtCduG/aOqpx/I
u0EgVKoUw4PWoz7keq4oi+xRwFmBhHDdj33LoND6wdL7bsEJyzxiBVrXqbu1jcAO
9a67+LNN4UcnSG6HXpUypdSQ+1I6yFn/FxZSyNpe3oeB3B06RkgIRu2rZJgCQk50
FrHMpritlRrKTMeCHRZ6jMMAEQEAAcLAgwQYAQoADwUCW6ve1wUJDwmcAAIbLgCo
CRBb4oJdFly3b50gBBkBCgAGBQJbq97XAAoJEPt0foEB3qiN24MD/it3xg5v+E8/
dL3/OdkPVekLrnnr7M27WxnMDtey5raMQLb9su3B3ured3O+8EA2hrDKH8kNKEaU
MH/r8lVY7tBOwrmwZbfQiqkWkaWEuVK8OcJFZypCO5DkuRA7lrgyVhtVr2nI4taa
NWwAJRIxy2+pG2TAOCmSe45VBc+R9P2aEBAEAIHaBZaGR5RJi0usQZtFPJl8n8TK
9se9QSkSFwGpaoH7/gStx0kEhUw9XRwWJEWb9buVUJlNmUBx6zpkWGuD1EYZilNV
QZ34fKZVQHPvOtIGHczPz4y7yas2nhC+pacwuT/ASUWh6b24fb10dnVzjdHwxNAo
ApMfX6zlllWH7MKrzo0EW6ve1wEEAL5EMktQaf+EXaLMseDrCdQeBVG1RcEP7gLz
IM+gvNgIoz+bCrAP7dTSzZr0qkoBzjlX/HBmWUyJXOE64FGHVX3EUCNFGRsxt345
BpIHcAxxq5DZtBRTv9i9SemNy1YUbsW3T4LtMvhYMjvmBqFFKYyQ9hlNXQLSJCtz
d7FYg0N9ABEBAAHCwIMEGAEKAA8FAlur3tcFCQ8JnAACGy4AqAkQW+KCXRZct2+d
IAQZAQoABgUCW6ve1wAKCRDs6w1N137UM0YABACvx9vRd332/zSt0Ll9HUfR5Sne
2d18PR2HolZHLyOp2Jhc8EGs+b90Z1naT0UPMtLZf3GBauBAyMAbQvnxmzDYEuU7
/kA/RaeqQ00qHleVPK68Cu2VlzQWGYha+yuKjYi9oDKr51+QTqXg9mHSFZ4std2x
KkNcgE7CJNzfeJ/Jq+LeA/46dSxmBfZ4vJz1SWfXEcnJsD1OUNR13oY3Y1IdaW7A
YXJx1P4euIxJpgF7irm0Cf6Y4JgKICNLs/AnjVp2BNhtAO97Urf6QHN4Ss7QGg7f
YwHrQqpuPVw3a+IQ+8EOcQZk/O+UTWEmMf13hdvwrUGVNDnHZwHhOdUajCLQluFE ZQ==
=h8z+ -----END PGP PUBLIC KEY BLOCK-----

On 1 Nov 2018 at 15:24, <Henk-Jan Lebbink <notifications@github.com>>
wrote:

The Microsoft.CodeAnalysis.CSharp.Scripting assembly is not found. What
version of VS and AsmDude are you using?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/HJLebbink/asm-dude/issues/90#issuecomment-435071030>,
or mute the thread

**Comment by pablohawk** [comment]
The PC in my office is using MS VS 2017 Community Version 15.8.7 with AsmDude 1.9.5.2
I will check my home PC and Classroom PC's tomorrow.
Paul
    On Thursday, November 1, 2018, 11:46:54 AM EDT, tjdowns <notifications@github.com> wrote:  
 
 Not interested.


-----BEGIN PGP PUBLIC KEY BLOCK----- Version: Keybase OpenPGP v1.0.0
Comment: https://keybase.io/crypto
xo0EW6ve1wEEANzWrHSRdb53la8ZDnFRYdoJbadLWpKmqJaRLFM6hxvU0YYOSaGn
b7iF5l2XRhkT2MIbWu5TuY1Las3BoR6bpZQk4AR84512lVqcQCgXH9aDdaRZr5Z4
bWGo/kzZ5xlhaGuJCebowocWMacy07GZwtXaTO2+dq9FlQJ1nvbNcX2HABEBAAHN
J1Rob21hcyBKLiBEb3ducyA8dGpkb3duc0Bob3RtYWlsLmNvLnVrPsKtBBMBCgAX
BQJbq97XAhsvAwsJBwMVCggCHgECF4AACgkQW+KCXRZct2872wP+J078WteXeh5O
Qs6hkKpCtWS06RzJ5c1zzLQZ+rmyWFmFbP16KP25L7SWc0gPAcQ+YvAayLEo/v7v
UTCLXtT2WM35v81iNWvq42wwoFiUjAjzvJZdmlxE0Jn5hxezes2hWINb21KOkzlG
orA7LCPJfPfQ4IQewd+9qzDYdwbWFinOjQRbq97XAQQAq/mXroCtCduG/aOqpx/I
u0EgVKoUw4PWoz7keq4oi+xRwFmBhHDdj33LoND6wdL7bsEJyzxiBVrXqbu1jcAO
9a67+LNN4UcnSG6HXpUypdSQ+1I6yFn/FxZSyNpe3oeB3B06RkgIRu2rZJgCQk50
FrHMpritlRrKTMeCHRZ6jMMAEQEAAcLAgwQYAQoADwUCW6ve1wUJDwmcAAIbLgCo
CRBb4oJdFly3b50gBBkBCgAGBQJbq97XAAoJEPt0foEB3qiN24MD/it3xg5v+E8/
dL3/OdkPVekLrnnr7M27WxnMDtey5raMQLb9su3B3ured3O+8EA2hrDKH8kNKEaU
MH/r8lVY7tBOwrmwZbfQiqkWkaWEuVK8OcJFZypCO5DkuRA7lrgyVhtVr2nI4taa
NWwAJRIxy2+pG2TAOCmSe45VBc+R9P2aEBAEAIHaBZaGR5RJi0usQZtFPJl8n8TK
9se9QSkSFwGpaoH7/gStx0kEhUw9XRwWJEWb9buVUJlNmUBx6zpkWGuD1EYZilNV
QZ34fKZVQHPvOtIGHczPz4y7yas2nhC+pacwuT/ASUWh6b24fb10dnVzjdHwxNAo
ApMfX6zlllWH7MKrzo0EW6ve1wEEAL5EMktQaf+EXaLMseDrCdQeBVG1RcEP7gLz
IM+gvNgIoz+bCrAP7dTSzZr0qkoBzjlX/HBmWUyJXOE64FGHVX3EUCNFGRsxt345
BpIHcAxxq5DZtBRTv9i9SemNy1YUbsW3T4LtMvhYMjvmBqFFKYyQ9hlNXQLSJCtz
d7FYg0N9ABEBAAHCwIMEGAEKAA8FAlur3tcFCQ8JnAACGy4AqAkQW+KCXRZct2+d
IAQZAQoABgUCW6ve1wAKCRDs6w1N137UM0YABACvx9vRd332/zSt0Ll9HUfR5Sne
2d18PR2HolZHLyOp2Jhc8EGs+b90Z1naT0UPMtLZf3GBauBAyMAbQvnxmzDYEuU7
/kA/RaeqQ00qHleVPK68Cu2VlzQWGYha+yuKjYi9oDKr51+QTqXg9mHSFZ4std2x
KkNcgE7CJNzfeJ/Jq+LeA/46dSxmBfZ4vJz1SWfXEcnJsD1OUNR13oY3Y1IdaW7A
YXJx1P4euIxJpgF7irm0Cf6Y4JgKICNLs/AnjVp2BNhtAO97Urf6QHN4Ss7QGg7f
YwHrQqpuPVw3a+IQ+8EOcQZk/O+UTWEmMf13hdvwrUGVNDnHZwHhOdUajCLQluFE ZQ==
=h8z+ -----END PGP PUBLIC KEY BLOCK-----

On 1 Nov 2018 at 15:24, <Henk-Jan Lebbink <notifications@github.com>>
wrote:

The Microsoft.CodeAnalysis.CSharp.Scripting assembly is not found. What
version of VS and AsmDude are you using?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/HJLebbink/asm-dude/issues/90#issuecomment-435071030>,
or mute the thread

**Comment by HJLebbink** [comment]
The Microsoft.CodeAnalysis.CSharp.Scripting assembly is part .NET Framework 4.6+, and this is a prerequisite of the extension. When installing AsmDude this .NET Framework will also be installed, but I guess you could force the installer not to do so.  Installing a .NET 4.6.2 (or higher) ought to resolve this issue. Let me know if this does not fix the issue.

**Comment by pablohawk** [comment]
So I have 4.7 installed at work, but no 4.6+.  I tried to install 4.6.2 but the webinstaller balked at me having a newer version.  So do I need a 4.6.x, or should 4.7 be working?

Sorry for being sporadic, I'm not in GITHUB often, but I do appreciate you responding.  This is not a production critical issue, but I teach Assembly at a University as an adjunct, and have been using AsmDude for the past 2 years.  It just started giving me the error with the latest upgrade.  I recommend AsmDude to my students, as they like seeing my code in color on the overhead.

**Comment by HJLebbink** [comment]
Version after 1.9.5.2 will have the expression evaluation switched off for syntax highlighting. It was too much hassle to get this to work on both VS2017 and 2015. You likely saw the missing library issue when parsing something as "10<<2" or "10>>2". Note that you now will have to put spaces between the << operator and constants for the constants to be recognized as such. Hope this helps.
